default_platform :ios

#https://docs.fastlane.tools/best-practices/continuous-integration/#application-specific-passwords
ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "uetj-geum-kuok-onqb"

ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

platform :ios do
    lane :reg_dev do
        register_devices(
          devices: {
            "Имя устройства (например Nikita 6s)" => "UDID устройства"
          }
        )
    end

    lane :build do
        gym(scheme: 'MedYuMed')
    end

    lane :deploy do
        match(type: "appstore", readonly: true)
        build
        pilot(skip_waiting_for_build_processing: true, username: "ownikss@yandex.ru", team_id: "119479835")
    end
end
