import { GlobalState } from '../lib/types';

// @ts-ignore
export const initialState: GlobalState = {
  app: {
    initialized: false,
    language: 'ru',
  },
  clubs: [],
  date: [],
  time: [],
  userInfo: {},
  user: {
    token: '',
    name: '',
    email: '',
    phone: '',
    birthday: '',
    surname: '',
    patronymic: '',
    balance: 0,
    clubs: [],
    exists: false,
    id: '',
    type: { name: '', id: '' },
  },
  comments: [],
  entry: {
    id: 0,
    service: '',
    price: '',
    master: '',
    employeeId: '',
    filial: '',
    clubId: '',
    date: '',
    time: '',
    serviceId: '',
    comment: '',
    title: '',
    typeDiscount: '',
    needBack: false,
  },
  entries: [],
  bonuses: [],
  confirmedEntries: [],
  appointmentServices: {},
  masters: [],
  popularCategories: [],
};
